language: swift
xcode_project: SwiftCollections.xcodeproj
xcode_scheme: SwiftCollections
osx_image: xcode9.2
script:
- xcodebuild -scheme SwiftCollections -project SwiftCollections.xcojeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' build test
after_success:
- bash <(curl -s https://codecov.io/bash)
